mwan3: roll back

diff --git a/net/mwan3/files/usr/sbin/mwan3 b/net/mwan3/files/usr/sbin/mwan3
--- a/net/mwan3/files/usr/sbin/mwan3
+++ b/net/mwan3/files/usr/sbin/mwan3
@@ -43,15 +43,9 @@ ifdown()
 
 ifup()
 {
-	local device enabled up l3_device status
+	local device enabled up l3_device
 
 	config_load mwan3
-	config_get_bool enabled globals 'enabled' 0
-	[ ${enabled} -gt 0 ] || {
-		echo "The service mwan3 is global disabled."
-		echo "Please execute \"/etc/init.d/mwan3 start\" first."
-		exit 1
-	}
 
 	if [ -z "$1" ]; then
 		echo "Expecting interface. Usage: mwan3 ifup <interface>" && exit 0
@@ -61,17 +55,19 @@ ifup()
 		echo "Too many arguments. Usage: mwan3 ifup <interface>" && exit 0
 	fi
 
-	status=$(ubus -S call network.interface.$1 status)
-	[ -n "$status" ] && {
-		json_load "$status"
-		json_get_vars up l3_device 
+	config_get_bool enabled globals 'enabled' 0
+	[ ${enabled} -gt 0 ] || {
+		echo "Warning: mwan3 is global disabled. Usage: /etc/init.d/mwan3 start"
+		exit 0
 	}
 
+	json_load $(ubus -S call network.interface.$1 status)
+	json_get_vars up l3_device
 	config_get enabled "$1" enabled 0
 
-	if [ "$up" = "1" ] \
+	if [ "$up" -eq 1 ] \
 		&& [ -n "$l3_device" ] \
-		&& [ "$enabled" = "1" ]; then
+		&& [ "$enabled" -eq 1 ]; then
 		ACTION=ifup INTERFACE=$1 DEVICE=$l3_device /sbin/hotplug-call iface
 	fi
 }
@@ -125,24 +121,39 @@ status()
 
 start()
 {
-	local enabled
+	local enabled src_ip local_source
 
-	uci_toggle_state mwan3 globals enabled "1"
+	config_load mwan3
+	config_get_bool enabled globals 'enabled' 0
+	[ ${enabled} -gt 0 ] || {
+		echo "Warning: mwan3 is global disabled. Usage: /etc/init.d/mwan3 start"
+		exit 0
+	}
+
+	config_get local_source globals local_source 'none'
+	[ "${local_source}" = "none" ] || {
+		src_ip=$(uci_get_state mwan3 globals src_ip)
+		[ "${src_ip}" != "" ] && {
+			ip route del default via "${src_ip}" dev lo 1>/dev/null 2>&1
+			ip addr del "${src_ip}/32" dev lo 1>/dev/null 2>&1
+		}
+
+		network_get_ipaddr src_ip "${local_source}"
+		if [ "${src_ip}" = "" ]; then
+			$LOG warn "Unable to set source ip for own initiated traffic (${local_source})"
+		else
+			ip addr add "${src_ip}/32" dev lo
+			ip route add default via "${src_ip}" dev lo
+			uci_toggle_state mwan3 globals src_ip "${src_ip}"
+		fi
+	}
 
 	config_foreach ifup interface
 }
 
 stop()
 {
-	local ipset route rule table IP IPT pid
-
-	mwan3_lock "command" "mwan3"
-
-	for pid in $(pgrep -f "mwan3rtmon"); do
-		kill -TERM "$pid" > /dev/null 2>&1
-		sleep 1
-		kill -KILL "$pid" > /dev/null 2>&1
-	done
+	local ipset route rule table IP IPT pid src_ip
 
 	for pid in $(pgrep -f "mwan3track"); do
 		kill -TERM "$pid" > /dev/null 2>&1
@@ -186,12 +197,14 @@ stop()
 		$IPS -q destroy $ipset
 	done
 
-	mwan3_unlock "command" "mwan3"
-
 	mwan3_lock_clean
 	rm -rf $MWAN3_STATUS_DIR $MWAN3TRACK_STATUS_DIR
 
-	uci_toggle_state mwan3 globals enabled "0"
+	src_ip=$(uci_get_state mwan3 globals src_ip)
+	[ "${src_ip}" = "" ] || {
+		ip route del default via "${src_ip}" dev lo 1>/dev/null 2>&1
+		ip addr del "${src_ip}/32" dev lo 1>/dev/null 2>&1
+	}
 }
 
 restart() {
